FirstProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^myCatalog/', include(('polls.urls',"polls"),namespace="polls")),
]

FirstProject/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('post/export',views.export, name="export"),
    path('post/delSong',views.delSong, name="delSong"),
    path('post/addSong', views.addSong, name="addSong"),
]

FirstProject/mysite/polls/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.

class Song(models.Model):
    songID = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    album = models.CharField(max_length=50)
    artist = models.CharField(max_length=150)
    publisher = models.CharField(max_length=30)
    date = models.DateField()

    def __str__(self):
        return "%s %s %s %s %s %s" % (self.songID, self.title, self.album, self.artist, self.publisher, self.date)

class User(models.Model):
    useId = models.AutoField(primary_key=True)
    userName = models.CharField(max_length=25)
    userPass = models.CharField(max_length=8)
    age = models.IntegerField(default=18,validators=[MinValueValidator(18)])
    joinDate = models.DateTimeField('date published')

    def __str__(self):
        return "%s %s %s %s %s" % (self.useId, self.userName, self.age, self.joinDate, self.userPass)

FirstProject/mysite/polls/forms.py
from django import forms

class HomeForm(forms.Form):
    Username = forms.CharField()
    Password = forms.CharField(max_length=32, widget=forms.PasswordInput)

FirstProject/mysite/polls/views.py
from django.shortcuts import render

from .models import Song,User
from .forms import HomeForm
from .resources import SongResource
from django.utils import timezone
# Create your views here.

def json2xml(myArray):
	myXML = ""
	for i in range(0,len(myArray)):
		for k,v in myArray[i].items():
			myXML += "<"+k+">\n\t"+str(v)+"\n</"+k+">"
		myXML += "\n"
	return myXML

def index(request):
    print("on Index Pages")
    form = HomeForm()
    context = {'form':form,'errMsg':''}
    return render(request, 'polls/index.html', context)

def post(request):
    users = User.objects.order_by("joinDate")
    form = HomeForm(request.POST)
    myUser=myPass=""
    valToken = 0
    if form.is_valid():
        myUser = form.cleaned_data['Username']
        myPass = form.cleaned_data['Password']
    for i in users:
        if(i.userName==myUser and i.userPass==myPass):
            valToken = 1
            break
    if valToken == 1:
        songs = Song.objects.order_by("date")
        context = {'form': form,'songs':songs}
        return render(request, 'polls/songCatalog.html', context)
    else:
        context = {'form': form,'errMsg':"Invalid Details!!"}
        return render(request, 'polls/index.html', context)

def delSong(request):
    if request.method == 'POST':
        delS = request.POST.getlist('delS')
    for i in range(0,len(delS)):
        Song.objects.filter(songID=delS[i]).delete()
    songs = Song.objects.order_by("date")
    context = {'songs': songs}
    print(type(delS))
    print(delS)
    return render(request, 'polls/songCatalog.html', context)

def export(request):
    if request.method == 'POST':
        exT = request.POST['expType']
    songR = SongResource()
    dataset = songR.export()
    js = dataset.json
    if(exT == "JSON"):
        result = js
    else:
        songs = Song.objects.order_by("date")
        myArray = []
        for i in songs:
            mydict = {"songID": i.songID, "title": i.title, "album": i.album, "artist": i.artist, "publisher": i.publisher, "date": i.date}
            myArray.append(dict(mydict))
        result = json2xml(myArray)
    return render(request, 'polls/detail.html', {'results': result})

def addSong(request):
    if request.method == 'POST':
        aTitle = request.POST['title']
        aAlbum = request.POST['album']
        aArtist = request.POST['artist']
        aPublisher = request.POST['publisher']
    instance = Song(title=aTitle, album=aAlbum, artist=aArtist, publisher=aPublisher, date=timezone.now())
    instance.save()
    songs = Song.objects.order_by("date")
    context = {'songs': songs}
    return render(request, 'polls/songCatalog.html', context)

FirstProject/mysite/polls/templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
</head>
<body>
<h1>MUSIC CATALOG</h1>
<hr>
{% block main_content %}
{% endblock %}
{% include "polls/footer.html" %}
</body>
</html>

FirstProject/mysite/polls/templates/polls/detail.html
<p>{{results}}</p>

FirstProject/mysite/polls/templates/polls/footer.html
<hr>
    <h3>Thank you for joining us!!</h3>
</hr>

FirstProject/mysite/polls/templates/polls/index.html
{% extends  'polls/base.html' %}

{% block main_content %}


<form method="post" action="{% url 'polls:post' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>


<h2>{{errMsg}}</h2>

{% endblock %}s

FirstProject/mysite/polls/templates/polls/songCatalog.html
{% extends  'polls/base.html' %}

{% block main_content %}

{% if songs %}
<h3>Our Music Collections.</h3>
    <form method="post" action="{% url 'polls:export'%}" target="_blank">
        {% csrf_token %}
        <h3>Export in
            <select name="expType">
                <option name="JSON">JSON</option>
                <option name="XML">XML</option>
            </select>
                <button type="submit">Export</button>
        </h3>
    </form>
<form method="post" action="{% url 'polls:delSong'%}">
    {% csrf_token %}
    <table id="songHolder">
        <tr><th>Song</th><th>Artist</th><th>Album</th><th>Publisher</th><th>Select To Delete</th></tr>
        {% for eachSong in songs %}
            <tr>
                <td>{{ eachSong.title }}</td>
                <td>{{eachSong.artist}}</td>
                <td>{{eachSong.album}}</td>
                <td>{{eachSong.publisher}}</td>
                <td><input type="checkbox" name="delS" value="{{eachSong.songID}}"></td>
            </tr>
        {% endfor %}
    </table>
    <button type="submit" style="position:relative;left:1100px">Delete Selected Songs</button>
</form>


{% else %}
    <p>No songs present in the catalog!!</p>
{% endif %}

<h2>{{errMsg}}</h2>

<form method="post" action="{% url 'polls:addSong'%}" id="addSong">
    {% csrf_token %}
    <h3>Add Song to Catalog</h3>
    <h4>Title:<input type="text" name="title" required>
    Album: <input type="text" name="album" required>
    Artist: <input type="text" name="artist" required>
    Publisher: <input type="text" name="publisher" required>
    <button type="submit">Add Song</button></h4>
</form>
{% endblock %}